# Colores oscuros
COLOR_DE_FONDO_DARK = "#141414"
COLOR_DE_TEXTO_DARK = "white"
COLOR_BOTONES_ESPECIALES_DARK = "#422b64"
COLOR_BOTONES_DARK = "#414141"
COLOR_CAJA_TEXTO_DARK = "#141414"

# Colores claros
COLOR_DE_FONDO_LIGHT = "#E0E0E0"
COLOR_DE_TEXTO_LIGHT = "black"
COLOR_BOTONES_ESPECIALES_LIGHT = "#D30069"
COLOR_BOTONES_LIGHT = "#F5F5F5"
COLOR_CAJA_TEXTO_LIGHT = "#E0E0E0"